export const consumerQuestions = [
  {
    key: "location",
    label: "Where are you located?",
    required: true,
    type: "text" as const,
    placeholder: "e.g. Nairobi, Westlands",
  },
  {
    key: "frequency",
    label: "How often do you buy prepared food?",
    required: true,
    type: "select" as const,
    options: ["Daily", "A few times a week", "Weekly", "Occasionally"],
  },
  {
    key: "budget",
    label: "Typical budget per meal?",
    required: false,
    type: "select" as const,
    options: ["< KES 200", "KES 200–500", "KES 500–1,000", "KES 1,000+"],
  },
  {
    key: "priority",
    label: "What do you care about most?",
    required: true,
    type: "select" as const,
    options: [
      "Price",
      "Taste",
      "Convenience",
      "Portion size",
      "Hygiene",
      "Delivery speed",
    ],
  },
  {
    key: "diet",
    label: "Any dietary preferences?",
    required: false,
    type: "select" as const,
    options: ["None", "Halal", "Vegan", "Vegetarian", "Gluten-free", "Other"],
  },
  {
    key: "invite_reason",
    label: "What would make you invite friends?",
    required: false,
    type: "textarea" as const,
    placeholder: "Discounts, early access, free delivery…",
  },
];
